### ISSUE TITLE
Indexing the same corpus twice will triple the storage

### ISSUE THREAD

**Issue by lannka** [fergiemcdowall/search-index#139]
I also tried to delete the doc before adding it back, but still getting the index file bigger and bigger. The search is working fine though, it's not returning duplicated entries, as I have manually assign the same doc IDs to those entries.

Is that working as intended? In my case, I do quite a lot doc update, so I'd have a cronjob updating the indices hourly/daily. How can I make sure it'll not quickly blow up the disk?

**Comment by fergiemcdowall** [comment]
Ahhh, yes. I think we may have stumbled upon a big here...

**Comment by mewwts** [comment]
I'm actually looking into this right now. Snapshotting the indexes after a doc is added once and then twice.

**Comment by mewwts** [comment]
After adding a simple doc once:
```
{"key":"DELETE-DOCUMENT~1~*","value":["*~~~","*~*~~","*~~~","*~*~~"]}
{"key":"DELETE-DOCUMENT~1~field1","value":["field1~~~","field1~*~~"]}
{"key":"DELETE-DOCUMENT~1~id","value":["id~~~","id~*~~"]}
{"key":"DOCUMENT~1~","value":{"id":1,"field1":1}}
{"key":"RI~*~*~~","value":[[21,"1"]]}
{"key":"RI~*~~~","value":[[21,"1"]]}
{"key":"RI~field1~*~~","value":[["11.0000000000","1"]]}
{"key":"RI~field1~~~","value":[["11.0000000000","1"]]}
{"key":"RI~id~*~~","value":[["11.0000000000","1"]]}
{"key":"RI~id~~~","value":[["11.0000000000","1"]]}
{"key":"TF~*~*~~","value":["1","1","1","1"]}
{"key":"TF~*~~~","value":["1","1","1","1"]}
{"key":"TF~field1~*~~","value":["1","1","1","1"]}
{"key":"TF~field1~~~","value":["1","1","1","1"]}
{"key":"TF~id~*~~","value":["1","1","1","1"]}
{"key":"TF~id~~~","value":["1","1","1","1"]}
{"key":"search-index.totalDocs","value":1}
```
After adding it twice

```
{"key":"DELETE-DOCUMENT~1~*","value":["*~~~","*~*~~","*~~~","*~*~~"]}
{"key":"DELETE-DOCUMENT~1~field1","value":["field1~~~","field1~*~~"]}
{"key":"DELETE-DOCUMENT~1~id","value":["id~~~","id~*~~"]}
{"key":"DOCUMENT~1~","value":{"id":1,"field1":1}}
{"key":"RI~*~*~~","value":[[21,"1"]]}
{"key":"RI~*~~~","value":[[21,"1"]]}
{"key":"RI~field1~*~~","value":[["11.0000000000","1"]]}
{"key":"RI~field1~~~","value":[["11.0000000000","1"]]}
{"key":"RI~id~*~~","value":[["11.0000000000","1"]]}
{"key":"RI~id~~~","value":[["11.0000000000","1"]]}
{"key":"TF~*~*~~","value":["1","1","1","1","1","1"]}
{"key":"TF~*~~~","value":["1","1","1","1","1","1"]}
{"key":"TF~field1~*~~","value":["1","1","1","1","1","1"]}
{"key":"TF~field1~~~","value":["1","1","1","1","1","1"]}
{"key":"TF~id~*~~","value":["1","1","1","1","1","1"]}
{"key":"TF~id~~~","value":["1","1","1","1","1","1"]}
{"key":"search-index.totalDocs","value":1}
````

It seems like the TF-fields are not overwritten, but rather appended to.

**Comment by fergiemcdowall** [comment]
Yes- that seems to be the problem

**Comment by lannka** [comment]
Thanks mewwts and fergiemcdowall.
Seems to me It will be hard to fix. Will this also affect the TF/IDF score?

One partial fix would be to clean up the TF-field before appending. However, it won't update those TF-fields that are in old doc but not new doc. 

I'm now wondering how the doc deletion work? Does it fix the TF-fields?

**Comment by fergiemcdowall** [comment]
Going to take a look at this...

**Comment by fergiemcdowall** [comment]
Should be fixed in 0.6.1

**Comment by fergiemcdowall** [comment]
@lannka the bug didnt affect the calculation logic, but it did cause changeable indexes to become bloated with redundant references since deletions were not cleaning everything up.

**Comment by lannka** [comment]
@fergiemcdowall I synced to 0.6.1, but seems the problem remains. First time the index is 160Mb, 2nd time 588Mb, 3rd time 657Mb. 

I also played it with the reuters corpus example, I repeated the same indexing multiple times, and recorded the index file size change as below:
6.4M 
11M
14M
13M
19M
14M
13M
19M
14M

I think the indexer is not idempotent?

**Comment by mewwts** [comment]
For one document like my example above, and with the reuters `justTen`, the output of the snapshot command is identical to me. However, the actual index size has grown.

After one indexing.
```
-rw-r--r--  1 mats  staff   149K Aug  4 09:02 000003.log
-rw-r--r--  1 mats  staff    16B Aug  4 09:02 CURRENT
-rw-r--r--  1 mats  staff     0B Aug  4 09:02 LOCK
-rw-r--r--  1 mats  staff    54B Aug  4 09:02 LOG
-rw-r--r--  1 mats  staff    50B Aug  4 09:02 MANIFEST-000002
```
After `rm -r` and 2  consecutive indexing jobs:
```
-rw-r--r--  1 mats  staff   397K Aug  4 09:03 000003.log
-rw-r--r--  1 mats  staff    16B Aug  4 09:03 CURRENT
-rw-r--r--  1 mats  staff     0B Aug  4 09:03 LOCK
-rw-r--r--  1 mats  staff    54B Aug  4 09:03 LOG
-rw-r--r--  1 mats  staff    50B Aug  4 09:03 MANIFEST-000002
```

**Comment by fergiemcdowall** [comment]
hmmm.. investigating...

**Comment by fergiemcdowall** [comment]
I just did this:

```bash
➜  search-index git:(master) ✗ while true; do ./node_modules/mocha/bin/mocha test/worldbank-tests/0-indexing-test.js > /dev/null && du -h test/sandbox/si-world-bank; done
 19M    test/sandbox/si-world-bank
 31M    test/sandbox/si-world-bank
 39M    test/sandbox/si-world-bank
 38M    test/sandbox/si-world-bank
 42M    test/sandbox/si-world-bank
 39M    test/sandbox/si-world-bank
 38M    test/sandbox/si-world-bank
 40M    test/sandbox/si-world-bank
 41M    test/sandbox/si-world-bank
 40M    test/sandbox/si-world-bank
 42M    test/sandbox/si-world-bank
```

Its seems that the index does grow initially, but only up to a certain point. I notice that if you generate the same index in two separate places, then you get two different sizes. If you re-add the documents to the same index, the content of the index _seems_ to always be the same, but the levelDB files are different

**Comment by fergiemcdowall** [comment]
So actually the contents of the indexes are not always the same. There is some reference duplication happening in the reverse index ('RI~') fields when you add and delete documents.

**Comment by fergiemcdowall** [comment]
Need to fix the RI thing...

**Comment by fergiemcdowall** [comment]
RI thing is now fixed which means that the index structure is always the same no matter how many times you delete and reindex stuff (thanks to @cshum's [PR](https://github.com/fergiemcdowall/search-index/commit/23a0c726cce5daeeeb8d374dec758c402d5af6e1)).

The size (in bytes) of the levelDB on disk will increase until it seems to "reset" itself. This appears to be a fairly harmless implementation feature, perhaps somebody who knows levelDB better can explain what is going on.

Either way, its fair to say that this is "fixed" as far as `search-index` is concerned

**Comment by mewwts** [comment]
:+1:
